version: '3.8'
services:
  nest:
    build:
      context: .
      target: dev
    init: true
    environment:
      - PORT=3001
      - DEBUG_HOST=0.0.0.0:9229
    command: npm run start:debug
    ports:
      - "127.0.0.1:3001:3001"
      - "127.0.0.1:9229:9229"
